require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
end

target 'App' do
  capacitor_pods
  # 2026-09-14: Google ログインは使っていない（providers は phone のみ）ので、
  # GoogleSignIn と RGCFA_INCLUDE_GOOGLE の手組みは外した。FirebaseAuth の版はプラグインの
  # 指定（~> 11.0）に任せて FirebaseCore と揃える。
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
